Repository canada-ca/ore-ero, pull requests merged in 2020-02, with the labels that each got.

#1005 Fix reset forms
  _includes/form/presets/partners.html
  assets/js/src/adminForm.js
  assets/js/src/codeForm.js
  assets/js/src/partners.js
  assets/js/src/partnershipForm.js
  assets/js/src/softwareForm.js
  assets/js/src/standardForm.js
Labels: bug

#1006 Redirect links are not available on open software page #998
  _data/i18n/tables.yml
  _includes/softwareTable.html
Labels: enhancement

#1000 adding multiples uses for each software
  _data/forms/config-software.yml
  _data/forms/param/date.yml
  _data/i18n/form.yml
  _includes/form/presets/uses.html
  _includes/schema/presets/uses.html
  assets/js/src/more-group.js
  assets/js/src/softwareForm.js
Labels: enhancement

#1008 Adding tests using Cypress
  .licensee.json
  assets/js/src/date.js
  assets/js/src/deep-object.js
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/unit-tests/code.spec.js
  cypress/integration/unit-tests/deep-object.spec.js
  cypress/integration/unit-tests/home.spec.js
  cypress/integration/unit-tests/partnership.spec.js
  cypress/integration/unit-tests/software-en-date.spec.js
  cypress/integration/unit-tests/software.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
Labels: tests

#1076 Added designs to metric page
  _data/i18n/general.yml
  _includes/statsDashboard.html
Labels: enhancement
